name: First Workflow
on: [push]


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      
      - name: mMultiline command
        run: |
          npm -v
          node -v