name: simple-checkoutaction-github
on: [push]

jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
          - name: List files before checkout
            run: ls -a
          - name: files checkout
            uses: actions/checkout@v4
          - name: list files after checkout
            run: ls -a