name: simple-checkoutaction-github
on: [push]

env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
          

          
          - name: Slack Notification
            uses: act10ns/slack@v1
            with:
              status: slack testing
              message: |
                :white_check_mark: slack testing
                :label: Commits: ${{ github.sha }}
                :link: Repository: ${{ github.repository }}
                :pushpin: Branch: ${{ github.ref }}
                author: ${{ github.event.head_commit.author.name }}
              channel: '${{ env.CHANNEL_ID }}'
            if: always() 

          - name: List files before checkout
            run: ls -a
          - name: files checkout
            uses: actions/checkout@v4
          - name: list files after checkout
            run: ls-a

          - name: Slack Notification
            uses: act10ns/slack@v1
            with:
              status: ${{ job.status }} for ${{ github.ref }}
              message: |
                :white_check_mark: Workflow ${GITHUB_WORKFLOW} job ${GITHUB_JOB} triggered by ${GITHUB_EVENT_NAME} is ${JOB_STATUS} for ${GITHUB_REF}
                ${COMMIT_SHA} - ${COMMIT_COUNT} commits
              channel: '${{ env.CHANNEL_ID }}'
            if: always()
          