name: Comment on Process Completion
on:
  push:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add a comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, GitHub } = require('@actions/github');
            const github = new GitHub(process.env.GITHUB_TOKEN);
            const { owner, repo } = context.repo;
            const comment = 'Process completed! 🎉';
            github.issues.createComment({
              owner,
              repo,
              issue_number: context.payload.workflow_run.head_repository.pull_requests[0].number,
              body: comment
            });
