name: Pre-Push Check

on:
  push:
    branches:
      - '*'

jobs:
  pre-push-check:
    name: Pre-Push Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      
      - name: Run pre-push script
        run: |
          #!/bin/bash
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if git fetch origin "$current_branch" &>/dev/null; then
              if git diff --quiet HEAD FETCH_HEAD; then
                  echo "Local branch '$current_branch' is up to date with the remote branch."
              else
                  echo "Local branch '$current_branch' is behind the remote branch. Please pull the latest changes before pushing."
                  exit 1
              fi
          else
              echo "Failed to fetch remote branch information. Please check your network connection and try again."
              exit 1
          fi
